services:
  servicio-notificador:
    build: ./servicio-notificaciones
    ports:
      - "8081:8080"

  servicio-solicitud:
    build: ./servicio-solicitudes
    ports:
      - "8080:8080"
    environment:
      #NOTIFICATION_URL: http://servicio-notificador:8080/notificaciones
      NOTIFICACIONES_URL: http://servicio-notificador:8080/solicitud-enviada
    depends_on:
      - servicio-notificador

