spring.application.name=servicio-solicitudes
notificaciones.url=${NOTIFICACIONES_URL:http://localhost:8081/solicitud-enviada}
notificaciones.aprobada-url=${NOTIFICACIONES_APROBADA_URL:http://localhost:8081/solicitud-aprobada}
